spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/remid_me?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
